apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
  limits:
    cpu: "20"
    memory: 128Gi
  template:
    metadata:
      labels:
        provisioned-by: karpenter
        usage: default
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3a.medium
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-southeast-2a
            - ap-southeast-2b
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand

      expireAfter: 720h # 30 * 24h = 720h
